function ftp=GetFtpLink(c)

% GetFtpLink.m : Extracts the ftp link in the string generated by horizons
% when the user asked for a ftp link
%
% PROTOTYPE :
%   ftp=GetFtpLink(c)
%
% DESCRIPTION
%   Extracts the ftp link in the string generated by horizons when the user
%   asked to have a ftp link
% 
%
% INPUT
%   c: the string generated by horizons when the user asked for a ftp link
%
% OUTPUT
%   ftp: the ftp link


i=1;
cur=c(i:i+8);

while not(isequal(cur,'Full path')) % looking for the words 'Full path' (the ftp link is just after)
    i=i+1;
    cur=c(i:i+8);
end

cur=c(i);

while cur~='f' % looking for the beginning of the ftp link
    i=i+1;
    cur=c(i);
end
index1=i;

while double(cur)~=10 && double(cur)~=13 % looking for the end of line (end of the ftp link)
    i=i+1;
    cur=c(i);
end

index2=i-1;

ftp=c(index1:index2); % extracting the ftp link